<article class="clearfix">
    <div class="row">
        <?php
        if (count($comments->items) > 0) {
        echo '<pre>';

        print_r($comments);
        echo '</pre>';
        foreach ($comments->items as $comment) { ?>
            <div class="col-sm-12">
                <div class="panel panel-white post panel-shadow">
                    <div class="post-heading">
                        <div class="pull-left image">
                            <img src="http://bootdey.com/img/Content/user_1.jpg"
                                 class="img-circle avatar" alt="user profile image">
                        </div>
                        <div class="pull-left meta">
                            <div class="title h5">
                                <a href="#"><b>Ryan Haywood</b></a>
                                made a post.
                            </div>
                            <h6 class="text-muted time"><?= $comment['date']; ?></h6>
                        </div>
                    </div>
                    <div class="post-description">
                        <p>Bootdey is a gallery of free snippets resources templates and utilities
                            for bootstrap css hmtl js framework. Codes for developers and web
                            designers</p>
                        <div class="stats">
                            <a style="color: green; padding: 5px;" href="#">
                                <span class="glyphicon glyphicon-thumbs-up"></span>
                                <i class="fa fa-thumbs-up icon"></i>2
                            </a>
                            <a style="color: red; padding: 5px;" href="#">
                                <span class="glyphicon glyphicon-thumbs-down"></span>
                                <i class="fa fa-thumbs-down icon"></i>12
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
    <?php
    include_once 'navigator.phtml';

    } ?>
</article>