<article class="post clearfix">
    <form id="comments" class="comments-form" method="post">
        <input type="hidden" name="user_id" value="<?= $_SESSION['user']['id'] ?>">
        <input type="hidden" name="post_id" value="<?= $post['id'] ?>">
        <div class="form-group">
            <label for="nombre">Nombre:</label>
            <input readonly value="<?= $_SESSION['user']['name'] . $_SESSION['user']['lastname'] ?>"
                   class="form-control" id="nombre" type="text" name="nombre"/>
        </div>
        <div class="form-group">
            <label for="email">Comment:</label><br>
            <textarea name="comment" id="comment" cols="50%" rows="5"></textarea>
        </div>
        <input type="submit" class="btn btn-success" value="enviar">
    </form>
</article>