<?php $this->assets->outputCss(); ?>
<section class="jumbotron">
    <div class="container">
        <h1>Gameloft Blog</h1>
        <p>Here something</p>
    </div>
</section>
<section class="main container">
    <div class="row">
        <section class="posts col-md-9">
            <div class="miga-de-pan">
                <ol class="breadcrumb">
                    <li><a href="#">Inicio</a></li>
                    <li><a href="#">Categorias</a></li>
                    <li class="active">Diseño Web</li>
                </ol>
            </div>
            <?php if (isset($posts)) {
                foreach ($posts->items as $post) {
                   /* echo '<pre>';
                    print_r($post);
                    echo '</pre>';*/

                    ?>
                    <article class="post clearfix">
                        <a href="#" class="thumb pull-left">
                            <img class="img-thumbnail" src="img/img2.jpg" alt="">
                        </a>
                        <h2 class="post-title">
                            <a href="#">Inicia proyectos HTML5 mas rápido con Initializr</a>
                        </h2>
                        <p><span class="post-fecha">26 de Enero de 2015</span> por <span class="post-autor"><a href="#">Carlos Arturo</a></span>
                        </p>
                        <p class="post-contenido text-justify">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        </p>

                        <div class="contenedor-botones">
                            <a href="./posts/show/<?=$post['id'];?>" class="btn btn-primary">Leer Mas</a>
                            <a href="#" class="btn btn-success">Comentarios <span class="badge">20</span></a>
                        </div>
                    </article>
                <?php } ?>
                <nav>
                    <div class="center-block">
                        <ul class="pagination">
                            <li><a href="/gl-blog/">Primera</a></li>
                            <li><a id="before" href="?p=<?= $posts->before; ?>">&laquo;<span
                                            class="sr-only">Anterior</span></a>
                            </li>
                            <?php for ($i = 1; $posts->total_pages >= $i; $i++) { ?>

                                <li><a id="page" href="?p=<?= $i; ?>"><?= $i; ?></a></li>
                                <?php
                                if ($i >= 10) {
                                    break;
                                }
                            }
                            if ($posts->current != $posts->total_pages) { ?>
                                <li><a id="next" href="?p=<?= $posts->next; ?>">&raquo;<span
                                                class="sr-only">Siguiente</span></a>
                                </li>
                                <li><a id="last" href="?p=<?= $posts->last; ?>">Ultima</a></li>
                            <?php } ?>
                        </ul>
                    </div>
                </nav>
            <?php } ?>
        </section>
        <aside class="col-md-3 hidden-xs hidden-sm">
            <h4>Categorias</h4>
            <div class="list-group">
                <a href="#" class="list-group-item active">Diseño Web</a>
                <a href="#" class="list-group-item">CSS</a>
                <a href="#" class="list-group-item">Cursos</a>
                <a href="#" class="list-group-item">Desarrollo Web</a>
                <a href="#" class="list-group-item">Elementos Web</a>
                <a href="#" class="list-group-item">Jquery</a>
                <a href="#" class="list-group-item">Recursos y Herramientas</a>
            </div>

            <h4>Articulos Recientes</h4>
            <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">Inicia proyectos HTML5 mas rápido con Initializr</h4>
                <p class="list-group-item-text">Aprende como iniciar un proyecto HTML5 en 15 minutos con Initialzr.</p>
            </a>

            <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">Como hacer una plantilla básica con PHP (templates)</h4>
                <p class="list-group-item-text">LoremAprende como transformar tu diseño web en una plantilla dinámica
                    con PHP.</p>
            </a>

            <a href="#" class="list-group-item">
                <h4 class="list-group-item-heading">Como cambiar el cursor de tu sitio web con propiedad CSS</h4>
                <p class="list-group-item-text">Aprende como cambiar el cursor de los elementos de tu sitio web con
                    CSS.</p>
            </a>
        </aside>
    </div>
</section>








