<?php $this->assets->outputCss();
//insert jumbotron
include_once C_PATH_LAYOUTS . 'jumbotron.phtml';
?>
<section class="main container">
    <div class="row">
        <section class="posts col-md-9">
            <div class="miga-de-pan">
                <ol class="breadcrumb">
                    <li><a href="#">Inicio</a></li>
                    <li><a href="#">Categorias</a></li>
                    <li class="active">Diseño Web</li>
                </ol>
            </div>
            <?php if (isset($posts)) {
                //include posts
                include_once C_PATH_LAYOUTS . 'index/posts.phtml';

                //insert page navigator
                include_once C_PATH_LAYOUTS . 'index/navigator.phtml';
            } ?>
        </section>
        <?php include_once C_PATH_LAYOUTS . 'aside.phtml' ?>
    </div>
</section>








