<?php $this->assets->outputCss();
include_once C_PATH_LAYOUTS . 'jumbotron.phtml';
?>
<section class="main container">
    <div class="row">
        <section class="posts col-md-9">
            <div class="miga-de-pan">
                <ol class="breadcrumb">
                    <li><a href="#">Inicio</a></li>
                    <li><a href="#">Categorias</a></li>
                    <li class="active">Diseño Web</li>
                </ol>
            </div>
            <article class="post clearfix">
                <?php include_once C_PATH_LAYOUTS . 'show/post.phtml'; ?>
                <h3>Comentarios</h3>
                <?php if (isset($comments)) {
                    include_once C_PATH_LAYOUTS . 'show/comments.phtml';

                } ?>
            </article>
            <h3>Deja tu comentario</h3>
            <?php
            include_once C_PATH_LAYOUTS . 'show/form_comments.phtml';

            ?>
        </section>
        <?php include_once C_PATH_LAYOUTS . 'aside.phtml'; ?>
    </div>
</section>








