<aside class="col-md-3 hidden-xs hidden-sm">
    <h4>Categorias</h4>
    <div class="list-group">
        <a href="#" class="list-group-item active">Diseño Web</a>
        <a href="#" class="list-group-item">CSS</a>
        <a href="#" class="list-group-item">Cursos</a>
        <a href="#" class="list-group-item">Desarrollo Web</a>
        <a href="#" class="list-group-item">Elementos Web</a>
        <a href="#" class="list-group-item">Jquery</a>
        <a href="#" class="list-group-item">Recursos y Herramientas</a>
    </div>

    <h4>Articulos Recientes</h4>
    <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">Inicia proyectos HTML5 mas rápido con Initializr</h4>
        <p class="list-group-item-text">Aprende como iniciar un proyecto HTML5 en 15 minutos con Initialzr.</p>
    </a>

    <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">Como hacer una plantilla básica con PHP (templates)</h4>
        <p class="list-group-item-text">LoremAprende como transformar tu diseño web en una plantilla dinámica
            con PHP.</p>
    </a>

    <a href="#" class="list-group-item">
        <h4 class="list-group-item-heading">Como cambiar el cursor de tu sitio web con propiedad CSS</h4>
        <p class="list-group-item-text">Aprende como cambiar el cursor de los elementos de tu sitio web con
            CSS.</p>
    </a>
</aside>