<nav id="footer" class="navbar navbar-default navbar-fixed-bottom">
    <footer id="footer">
        <div class="container container-fluid">
            <section id="content-foote">
                <ul class="pull-left nav navbar-nav">
                    <li class=""><a href="#">&copy; Gameloft - 2017 | Gameloft Blog</a></li>
                </ul>
                <ul class="pull-right nav navbar-nav">
                    <li class="active"><a href="#">About</a></li>
                    <li class="active"><a href="#">Contact</a></li>
                </ul>
            </section>
        </div>
    </footer>
</nav>
<?php $this->assets->outputJs(); ?>
<span class="to-clouds glyphicon glyphicon-menu-up"></span>
</body>
</html>