<div class="container">
    <div class="card card-container">
        <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
        <img id="profile-img" class="profile-img-card" src="/gl-blog/public/img/logo.png"/>
        <p id="profile-name" class="profile-name-card"></p>
        <form id="form-sigin" method="post" action="/gl-blog/accounts/login/" class="form-signin">
            <span id="reauth-email" class="reauth-email"><h2>Inicia sesion</h2></span>
            <div class="form-group">

                <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address"
                       required
                       autofocus>
            </div>
            <div class="form-group">

                <input type="password" name="auth" id="inputPassword" class="form-control" placeholder="Password"
                       required>
            </div>
            <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Login</button>
        </form>
    </div><!-- /card-container -->
</div><!-- /container -->

